/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import Courses.Course;
import JSON.CourseService;
import JSON.StudentService;
import Users.Student;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class BrowseEnrollCourses extends javax.swing.JFrame {

    /**
     * Creates new form BrowseEnrollCourses
     */
  private Student student;
    private StudentService studentService;
    private CourseService courseService;

    public BrowseEnrollCourses(Student student, StudentService studentService, CourseService courseService) {
        this.student = student;
        this.studentService = studentService;
        this.courseService = courseService;

        initComponents();
        setupTable();
    }

  private void setupTable() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Course ID", "Title"}, 0
        );
        coursesTable.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        browseBtn = new javax.swing.JButton();
        enrollBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        viewLessonsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(coursesTable);

        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        enrollBtn.setText("Enroll");
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        viewLessonsBtn.setText("View Lessons ");
        viewLessonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLessonsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(enrollBtn)
                .addGap(18, 18, 18)
                .addComponent(browseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewLessonsBtn)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseBtn)
                    .addComponent(enrollBtn)
                    .addComponent(backBtn)
                    .addComponent(viewLessonsBtn))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) coursesTable.getModel();
        model.setRowCount(0);

        List<Course> courses = studentService.browseCourses();

        if (courses == null || courses.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No courses available.");
            return;
        }

        for (Course c : courses) {
            model.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle()
            });
        }
    }//GEN-LAST:event_browseBtnActionPerformed

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBtnActionPerformed
        // TODO add your handling code here:
        int row = coursesTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }

        String courseId = coursesTable.getValueAt(row, 0).toString();

        boolean ok = student.enrollCourse(courseId);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Enrolled successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Already enrolled.");
        }
    }//GEN-LAST:event_enrollBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new CourseManagementStudent(student, studentService, courseService).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewLessonsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLessonsBtnActionPerformed
        // TODO add your handling code here:
           int row = coursesTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

   
    String courseId = coursesTable.getValueAt(row, 0).toString();
    new LessonManagement(student, studentService, courseService, courseId).setVisible(true);

    this.dispose();
    }//GEN-LAST:event_viewLessonsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JTable coursesTable;
    private javax.swing.JButton enrollBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewLessonsBtn;
    // End of variables declaration//GEN-END:variables
}
